// <auto-generated />
using CarShop.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240101154154_AddProductToDbAndSeed")]
    partial class AddProductToDbAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShop.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Hyundai"
                        });
                });

            modelBuilder.Entity("CarShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Седан"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Купе"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Хэтчбек"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Лифтбек"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Фастбек"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Универсал"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Кроссовер"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Внедорожник"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Пикап"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Легковой фургон"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Минивен"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Компактвен"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Микровен"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Кабриолет"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Родстер"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Тарга"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "Ландо"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Лимузин"
                        });
                });

            modelBuilder.Entity("CarShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("basicEquipmentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("fullEquipmentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarName = "BMW 318i",
                            Description = "Мощность двигателя: 156 л.с\nРасход топлива: 6,3 л/100 км",
                            basicEquipmentPrice = 120000m,
                            fullEquipmentPrice = 2000000m
                        },
                        new
                        {
                            Id = 2,
                            CarName = "BMW X6 M50i",
                            Description = "Мощность двигателя: 480 л.с.\nРасход топлива в л/100км (смешанный цикл): 11.5",
                            basicEquipmentPrice = 1000000m,
                            fullEquipmentPrice = 180000m
                        },
                        new
                        {
                            Id = 3,
                            CarName = "Mercedes-Benz C118/X118",
                            Description = "Мощность двигателя: 421 л.с.\nРасход топлива: 9.2 на 100 км",
                            basicEquipmentPrice = 1500000m,
                            fullEquipmentPrice = 2000000m
                        },
                        new
                        {
                            Id = 4,
                            CarName = "Nissan Tiida",
                            Description = "Мощность двигателя: 128 л.с.\nРасход топлива: 4.7-10.1 л/100 км",
                            basicEquipmentPrice = 700000m,
                            fullEquipmentPrice = 850000m
                        },
                        new
                        {
                            Id = 5,
                            CarName = "Toyota Sequoia",
                            Description = "Мощность двигателя: 437 л.с.n\nРасход топлива: 11.7-23 л/100 км",
                            basicEquipmentPrice = 1200000m,
                            fullEquipmentPrice = 1400000m
                        },
                        new
                        {
                            Id = 6,
                            CarName = "Kia XCeed",
                            Description = "Мощность двигателя: 200 л.с.n\nРасход топлива: 7.1 л/100 км",
                            basicEquipmentPrice = 600000m,
                            fullEquipmentPrice = 750000m
                        },
                        new
                        {
                            Id = 7,
                            CarName = "Honda Civic 1.0",
                            Description = "Мощность двигателя: 129 л.с.n\nРасход топлива: 5.5 л/100 км",
                            basicEquipmentPrice = 600000m,
                            fullEquipmentPrice = 750000m
                        },
                        new
                        {
                            Id = 8,
                            CarName = "HYUNDAI Tucson",
                            Description = "Мощность двигателя: 185 л.с.n\nРасход топлива: 5.4 л/100 км",
                            basicEquipmentPrice = 600000m,
                            fullEquipmentPrice = 750000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
